;;; photon-test.el --- Tests for photon.el -*- lexical-binding: t; -*-

(require 'ert)
(add-to-list 'load-path "lisp")
(require 'photon)

(ert-deftest photon-chunk-tokens-preserves-order ()
  (should (equal (photon-chunk-tokens '(1 2 3 4 5) 2)
                 '((1 2) (3 4) (5)))))

(ert-deftest photon-forward-has-bounded-local-shape ()
  (let* ((config (photon-make-config 12 6 3 2))
         (states (photon-forward config '(1 2 3 4 5))))
    ;; Two chunks at chunk-size 3 decode into six local positions.  The final
    ;; partial chunk is padded only inside the bounded local decoder.
    (should (= (length states) 6))
    (should (= (length (car states)) 6))))

(ert-deftest photon-prediction-state-uses-last-real-token ()
  (let* ((config (photon-make-config 12 6 2 2))
         (tokens '(1 2 3))
         (states (photon-forward config tokens)))
    (should (eq (photon-prediction-state states tokens)
                (nth 2 states)))
    (should-not (eq (photon-prediction-state states tokens)
                    (car (last states))))))

(ert-deftest photon-generation-is-deterministic ()
  (let* ((config (photon-make-config 16 8 4 2))
         (left (photon-generate config '(1 3 5) 3))
         (right (photon-generate config '(1 3 5) 3)))
    (should (equal left right))
    (should (= (length left) 6))))

(ert-deftest photon-training-pairs-use-fixed-context ()
  (should (equal (photon-training-pairs '(1 2 3 4 5) 3)
                 '(((1 2 3) . 4)
                   ((2 3 4) . 5)))))

(ert-deftest photon-training-pairs-handle-short-input ()
  (should (equal (photon-training-pairs '(1 2) 3) nil)))

(ert-deftest photon-vector-backend-defaults-to-list ()
  (let ((photon-vector-backend (photon-make-list-vector-backend)))
    (should (eq (photon-vector-backend-name) 'list-vector))
    (should (equal (photon-vector-to-list
                    (photon-vector-add (photon-vector-from-list '(1.0 2.0))
                                       (photon-vector-from-list '(3.0 4.0))))
                   '(4.0 6.0)))
    (should (= (photon-vector-dot (photon-vector-from-list '(1.0 2.0))
                                  (photon-vector-from-list '(3.0 4.0)))
               11.0))))

(ert-deftest photon-vector-backend-supports-elementwise-mul ()
  (let ((photon-vector-backend (photon-make-elisp-vector-backend)))
    (should (equal (photon-vector-to-list
                    (photon-vector-mul (photon-vector-from-list '(2.0 3.0))
                                       (photon-vector-from-list '(4.0 5.0))))
                   '(8.0 15.0)))))

(ert-deftest photon-vector-backend-selects-by-name ()
  (let ((photon-vector-backend (photon-make-list-vector-backend)))
    (photon-use-vector-backend-name "elisp-vector")
    (should (eq (photon-vector-backend-name) 'elisp-vector))
    (photon-use-vector-backend-name 'elisp-tensor)
    (should (eq (photon-vector-backend-name) 'elisp-tensor))
    (photon-use-vector-backend-name "list-vector")
    (should (eq (photon-vector-backend-name) 'list-vector))
    (should-error (photon-use-vector-backend-name "missing-backend"))))

(ert-deftest photon-vector-library-supports-matrix-vector-dot ()
  (let ((photon-vector-backend (photon-make-elisp-vector-backend)))
    (let ((matrix (photon-matrix-from-rows
                   (list (photon-vector-from-list '(1.0 2.0))
                         (photon-vector-from-list '(3.0 4.0)))))
          (vec (photon-vector-from-list '(10.0 20.0))))
      (should (equal (photon-matrix-shape matrix) '(2 2)))
      (should (equal (photon-vector-to-list
                      (photon-matrix-vector-dot matrix vec))
                     '(50.0 110.0))))))

(ert-deftest photon-vector-library-reports-tensor-shape ()
  (let ((photon-vector-backend (photon-make-elisp-vector-backend)))
    (should (photon-vector-backend-supports-p 'tensor))
    (should (equal (photon-tensor-shape
                    (list (photon-vector-from-list '(1.0 2.0))
                          (photon-vector-from-list '(3.0 4.0))))
                   '(2 2)))))

(ert-deftest photon-elisp-tensor-backend-supports-matrix-and-tensor-ops ()
  (let ((photon-vector-backend (photon-make-elisp-tensor-backend)))
    (should (eq (photon-vector-backend-name) 'elisp-tensor))
    (should (photon-vector-backend-supports-p 'tensor))
    (let* ((matrix (photon-matrix-from-rows
                    (list (photon-vector-from-list '(1.0 2.0))
                          (photon-vector-from-list '(3.0 4.0)))))
           (vec (photon-vector-from-list '(10.0 20.0)))
           (tensor (photon-tensor-zeros '(2 2)))
           (scaled (photon-tensor-scale 2.0
                                        (photon-tensor-add tensor tensor))))
      (should (vectorp matrix))
      (should (equal (photon-matrix-shape matrix) '(2 2)))
      (should (equal (photon-vector-to-list
                      (photon-matrix-vector-dot matrix vec))
                     '(50.0 110.0)))
      (should (equal (photon-tensor-shape scaled) '(2 2))))))

(defun photon-test-external-matrix-shape (_matrix)
  '(external 2 3))

(defun photon-test-external-tensor-shape (_tensor)
  '(external-tensor 2 3 4))

(ert-deftest photon-vector-external-backend-can-override-shape-ops ()
  (let ((photon-vector-backend
         (photon-make-external-vector-backend
          'external-test
          '(vector matrix tensor)
          (list (cons 'add 'photon-list-vector-add)
                (cons 'mul 'photon-list-vector-mul)
                (cons 'matvec 'photon-list-matrix-vector-dot)
                (cons 'scale 'photon-list-vector-scale)
                (cons 'dot 'photon-list-vector-dot)
                (cons 'squash 'photon-list-vector-squash)
                (cons 'from-list 'photon-list-vector-from-list)
                (cons 'to-list 'photon-list-vector-to-list)
                (cons 'zeros 'photon-list-vector-zeros)
                (cons 'matrix-shape
                      'photon-test-external-matrix-shape)
                (cons 'tensor-shape
                      'photon-test-external-tensor-shape)))))
    (should (eq (photon-vector-backend-name) 'external-test))
    (should (equal (photon-matrix-shape 'ignored) '(external 2 3)))
    (should (equal (photon-tensor-shape 'ignored)
                   '(external-tensor 2 3 4)))))

(ert-deftest photon-vector-fingerprint-is-stable-and-compact ()
  (let ((photon-vector-backend (photon-make-elisp-vector-backend)))
    (let ((left (photon-vector-from-list '(1.0 2.0 3.0 4.0)))
          (right (photon-vector-from-list '(1.0 2.0 3.0 5.0))))
      (should (equal (photon-vector-fingerprint left)
                     (photon-vector-fingerprint left)))
      (should-not (equal (photon-vector-fingerprint left)
                         (photon-vector-to-list left)))
      (should-not (equal (photon-vector-fingerprint left)
                         (photon-vector-fingerprint right))))))

(ert-deftest photon-vector-backend-supports-elisp-vector ()
  (let ((photon-vector-backend (photon-make-elisp-vector-backend)))
    (should (eq (photon-vector-backend-name) 'elisp-vector))
    (should (photon-vector-backend-supports-p 'vector))
    (should (photon-vector-backend-supports-p 'matrix))
    (should (photon-vector-backend-supports-p 'tensor))
    (should (photon-vector-backend-supports-p 'elementwise))
    (should (photon-vector-backend-supports-p 'fingerprint))
    (should (equal (photon-vector-to-list
                    (photon-vector-add (photon-vector-from-list '(1.0 2.0))
                                       (photon-vector-from-list '(3.0 4.0))))
                   '(4.0 6.0)))
    (should (= (photon-vector-dot (photon-vector-from-list '(1.0 2.0))
                                  (photon-vector-from-list '(3.0 4.0)))
               11.0))))

(ert-deftest photon-stream-training-matches-pair-evaluation-counts ()
  (let* ((config (photon-make-config 8 8 4 2))
         (model-a (photon-make-model config))
         (model-b (photon-make-model config))
         (tokens '(1 2 3 4 1 2 3 4)))
    (should (equal (photon-train-epoch model-a
                                       (photon-training-pairs tokens 4)
                                       0.0)
                   (photon-train-epoch-stream model-b tokens 4 0.0)))))

(ert-deftest photon-minibatch-training-improves-toy-corpus ()
  (let* ((photon-vector-backend (photon-make-elisp-vector-backend))
         (config (photon-make-config 8 8 4 2))
         (model (photon-make-model config))
         (corpus '(1 2 3 4 1 2 3 4 1 2 3 4))
         (before (cdr (assq 'correct (photon-evaluate model corpus 4)))))
    (photon-train-minibatch model corpus 4 4 0.35 4)
    (let ((after (cdr (assq 'correct (photon-evaluate model corpus 4)))))
      (should (>= after before)))))

(ert-deftest photon-model-has-trainable-embedding-table ()
  (let* ((photon-vector-backend (photon-make-elisp-vector-backend))
         (config (photon-make-config 8 8 4 2))
         (model (photon-make-model config))
         (embedding (nth 1 (photon-model-embedding-table model))))
    (should (= (length (photon-model-embedding-table model)) 8))
    (should (= (length embedding) 8))))

(ert-deftest photon-model-has-target-prototype-memory ()
  (let* ((photon-vector-backend (photon-make-elisp-vector-backend))
         (config (photon-make-config 8 8 4 2))
         (model (photon-make-model config)))
    (should (= (length (photon-model-target-prototypes model)) 8))
    (should (= (length (car (photon-model-target-prototypes model))) 8))
    (should (= (length (photon-model-target-counts model)) 8))
    (should-not (photon-model-target-state-clusters model))
    (should (photon-model-next-token-memory-enabled-p model))
    (should (= (photon-model-next-token-memory-limit model) 512))
    (photon-model-remember-next-token model '(1 2 3 4) 5)
    (should (photon-model-next-token-memory-hit-p model '(1 2 3 4)))
    (should (= (photon-model-next-token-memory-get model '(1 2 3 4)) 5))
    (photon-model-param-set model 'next-token-memory-enabled 0.0)
    (should-not (photon-model-next-token-memory-enabled-p model))
    (should-not (photon-model-next-token-memory-hit-p model '(1 2 3 4)))
    (should-not (photon-model-next-token-memory-get model '(1 2 3 4)))))

(ert-deftest photon-training-rebuilds-target-state-clusters ()
  (let* ((photon-vector-backend (photon-make-elisp-vector-backend))
         (config (photon-make-config 8 8 4 2))
         (model (photon-make-model config))
         (corpus '(1 2 3 4 1 2 3 4 1 2 3 4)))
    (photon-train model corpus 4 2 0.20)
    (let ((clusters (photon-model-target-state-clusters model)))
      (should (consp clusters))
      (should (assq 1 clusters))
      (should (<= (length (cdr (assq 1 clusters)))
                  (photon-model-target-state-cluster-limit model))))))

(ert-deftest photon-context-anchor-weight-learns-from-context ()
  (let* ((photon-vector-backend (photon-make-elisp-vector-backend))
         (config (photon-make-config 8 4 2 2))
         (model (photon-make-model config)))
    (photon-model-param-set model 'next-token-memory-enabled 0.0)
    (should (= (photon-model-param-get model 'context-anchor-weight) 0.0))
    (photon-train model '(1 2 3 1 2) 3 1 0.20)
    (should (> (photon-model-param-get model 'context-anchor-weight) 0.0))
    (should (= (cdr (assq 'accuracy-permil
                          (photon-evaluate model '(2 3 1 2 3) 3)))
               1000))))

(ert-deftest photon-training-updates-embedding-table ()
  (let* ((photon-vector-backend (photon-make-elisp-vector-backend))
         (config (photon-make-config 8 8 4 2))
         (model (photon-make-model config))
         (corpus '(1 2 3 4 1 2 3 4 1 2 3 4))
         (before (photon-vector-to-list
                  (nth 1 (photon-model-embedding-table model)))))
    (photon-train model corpus 4 2 0.20)
    (let ((after (photon-vector-to-list
                  (nth 1 (photon-model-embedding-table model)))))
      (should-not (equal before after)))))

(ert-deftest photon-model-has-architecture-params ()
  (let* ((config (photon-make-config 8 8 4 2))
         (model (photon-make-model config)))
    (should (= (photon-model-param-get model 'chunk-scale) 1.0))
    (should (= (photon-model-param-get model 'context-current) 0.72))
    (should (= (photon-model-param-get model 'decoder-prev) 0.35))
    (should (= (photon-model-param-get model 'decoder-token-mix) 1.0))
    (should (= (photon-model-param-get model 'context-anchor-recency) 0.70))
    (should (= (photon-model-param-get model 'context-anchor-prefix-weight) 1.0))
    (should (= (photon-model-param-get model 'wordpiece-context-anchor-ngram-weight) 6.0))
    (should (= (photon-model-param-get model 'wordpiece-long-token-update-weight) 0.35))
    (should (= (photon-model-param-get model 'wordpiece-rare-token-update-weight) 0.50))
    (should (= (photon-model-param-get model 'wordpiece-update-scale-max) 2.50))
    (should (= (photon-model-param-get model 'wordpiece-readout-bias-enabled) 0.0))
    (should (= (photon-model-param-get model 'wordpiece-long-readout-bias-weight) 0.75))
    (should (= (photon-model-param-get model 'wordpiece-rare-readout-bias-weight) 0.50))
    (should (= (photon-model-param-get model 'wordpiece-readout-bias-max) 2.50))
    (should (= (photon-model-param-get model 'wordpiece-ngram-rescue-weight) 1.00))
    (should (= (photon-model-param-get model 'wordpiece-ngram-rescue-epochs) 4.0))
    (should (= (photon-model-param-get model 'context-anchor-ngram-contrastive-weight) 0.25))
    (should (= (photon-model-param-get model 'context-anchor-weight-max) 1.0))
    (should (= (photon-model-param-get model 'char-class-bias-weight) 0.75))
    (should (= (photon-model-param-get model 'char-boundary-bias-weight) 1.0))
    (should (= (photon-model-param-get model 'structural-boundary-bias-weight) 0.10))
    (should (= (photon-model-param-get model 'structural-bias-letter-gate-scale) 0.0))
    (should (= (photon-model-param-get model 'structural-bias-space-gate-scale) 0.75))
    (should (= (photon-model-param-get model 'structural-tie-breaker-weight) 2.0))
    (should (= (photon-model-param-get model 'newline-boundary-bonus) 4.20))
    (should (= (photon-model-param-get model 'generation-repeat-bias-weight) 1.25))
    (should (= (photon-model-param-get model 'generation-newline-run-bias-weight) 3.0))
    (should (= (photon-model-param-get model 'generation-space-run-bias-weight) 1.0))
    (should (= (photon-model-param-get model 'wordpiece-generation-repeat-bias-weight) 2.50))
    (should (= (photon-model-param-get model 'wordpiece-generation-continuation-run-bias-weight) 1.50))
    (should (= (photon-model-param-get model 'wordpiece-generation-recent-token-bias-weight) 0.40))
    (should (= (photon-model-param-get model 'wordpiece-generation-recent-token-window) 8.0))
    (should (= (photon-model-param-get model 'output-head-aux-update-weight) 0.50))
    (should (= (photon-model-param-get model 'output-head-anchor-distill-weight) 2.50))
    (should (= (photon-model-param-get model 'output-head-cluster-distill-weight) 1.00))
    (should (= (photon-model-param-get model 'output-head-cluster-distill-epochs) 5.0))
    (should (= (photon-model-param-get model 'output-head-prototype-weight) 8.0))
    (should (= (photon-model-param-get model 'output-head-prototype-limit) 8.0))
    (should (= (photon-model-param-get model 'output-head-linear-readout-weight) 0.0))
    (should (= (photon-model-param-get model 'output-head-compress-weight) 0.40))
    (should (= (photon-model-param-get model 'output-head-compress-epochs) 12.0))
    (should (= (photon-model-param-get model 'output-head-ngram-distill-weight) 0.50))
    (should (= (photon-model-param-get model 'prototype-ngram-distill-weight) 1.00))
    (should (= (photon-model-param-get model 'output-head-state-cluster-readout-weight) 1.0))
    (should (= (photon-model-param-get model 'state-cluster-readout-weight) 1.0))
    (should (= (photon-model-param-get model 'state-cluster-limit) 64.0))
    (should (= (photon-model-param-get model 'next-token-weight) 1.0))
    (should (= (photon-model-param-get model 'reconstruction-weight) 0.05))
    (should (= (photon-model-param-get model 'next-context-weight) 0.02))))

(ert-deftest photon-training-updates-architecture-params ()
  (let* ((photon-vector-backend (photon-make-elisp-vector-backend))
         (config (photon-make-config 8 8 4 2))
         (model (photon-make-model config))
         (corpus '(1 2 3 4 1 2 3 4 1 2 3 4))
         (before (copy-tree (photon-model-architecture-params model))))
    (photon-train model corpus 4 2 0.20)
    (should-not (equal before (photon-model-architecture-params model)))))

(ert-deftest photon-model-has-layer-gain-vectors ()
  (let* ((photon-vector-backend (photon-make-elisp-vector-backend))
         (config (photon-make-config 8 8 4 2))
         (model (photon-make-model config))
         (gain (photon-model-gain-get model 'chunk-gain)))
    (should (= (length (photon-model-layer-gains model)) 5))
    (should (= (length gain) 8))))

(ert-deftest photon-model-has-layer-projection-matrices ()
  (let* ((photon-vector-backend (photon-make-elisp-vector-backend))
         (config (photon-make-config 8 8 4 2))
         (model (photon-make-model config))
         (projection (photon-model-projection-get model 'chunk-proj)))
    (should (= (length (photon-model-layer-projections model)) 4))
    (should (equal (photon-projection-shape projection) '(8 8)))
    (should (eq (cdr (assq 'kind projection)) 'low-rank))))

(ert-deftest photon-model-has-output-head-projection ()
  (let* ((photon-vector-backend (photon-make-elisp-vector-backend))
         (config (photon-make-config 8 8 4 2))
         (model (photon-make-model config))
         (projection (photon-model-output-head-projection model)))
    (should (equal (photon-projection-shape projection) '(8 8)))
    (should (eq (cdr (assq 'kind projection)) 'low-rank))))

(ert-deftest photon-training-updates-layer-gain-vectors ()
  (let* ((photon-vector-backend (photon-make-elisp-vector-backend))
         (config (photon-make-config 8 8 4 2))
         (model (photon-make-model config))
         (corpus '(1 2 3 4 1 2 3 4 1 2 3 4))
         (before (photon-vector-to-list
                  (photon-model-gain-get model 'chunk-gain))))
    (photon-train model corpus 4 2 0.20)
    (let ((after (photon-vector-to-list
                  (photon-model-gain-get model 'chunk-gain))))
      (should-not (equal before after)))))

(ert-deftest photon-training-updates-layer-projections ()
  (let* ((photon-vector-backend (photon-make-elisp-vector-backend))
         (config (photon-make-config 8 8 4 2))
         (model (photon-make-model config))
         (corpus '(1 2 3 4 1 2 3 4 1 2 3 4))
         (before (copy-tree (photon-model-projection-get model 'chunk-proj))))
    (photon-train model corpus 4 2 0.20)
    (should-not (equal before (photon-model-projection-get model 'chunk-proj)))))

(ert-deftest photon-model-project-caches-results ()
  (let* ((photon-vector-backend (photon-make-elisp-vector-backend))
         (config (photon-make-config 8 8 4 2))
         (model (photon-make-model config))
         (vec (photon-vector-from-list '(1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0))))
    (photon-model-project model 'chunk-proj vec)
    (should (= (length (photon-model-cache model)) 1))
    (photon-model-project model 'chunk-proj vec)
    (should (= (length (photon-model-cache model)) 1))
    (photon-update-layer-projections model 1 2 0.1)
    (should (= (length (photon-model-cache model)) 0))))

(ert-deftest photon-model-token-embedding-caches-by-token ()
  (let* ((photon-vector-backend (photon-make-elisp-vector-backend))
         (config (photon-make-config 8 8 4 2))
         (model (photon-make-model config))
         (key (photon-token-cache-key 1)))
    (photon-model-clear-cache model)
    (photon-model-token-embedding model 1)
    (should (photon-model-cache-get model key))
    (should (= (length (photon-model-cache model)) 1))
    (photon-model-token-embedding model 1)
    (should (= (length (photon-model-cache model)) 1))
    (photon-update-embedding-table model '(1) 1 2 0.1)
    (should (= (length (photon-model-cache model)) 0))))

(ert-deftest photon-forward-model-caches-by-window ()
  (let* ((photon-vector-backend (photon-make-elisp-vector-backend))
         (config (photon-make-config 8 8 4 2))
         (model (photon-make-model config))
         (context '(1 2 3 4))
         (key (photon-window-cache-key context)))
    (photon-model-clear-cache model)
    (photon-forward-model model context)
    (should (photon-model-cache-get model key))
    (let ((cache-size (length (photon-model-cache model))))
      (photon-forward-model model context)
      (should (= (length (photon-model-cache model)) cache-size)))
    (photon-model-param-set model 'chunk-scale 1.1)
    (should (= (length (photon-model-cache model)) 0))))

(ert-deftest photon-predict-one-caches-by-window ()
  (let* ((photon-vector-backend (photon-make-elisp-vector-backend))
         (config (photon-make-config 8 8 4 2))
         (model (photon-make-model config))
         (context '(1 2 3 4))
         (key (photon-prediction-cache-key context)))
    (photon-model-clear-cache model)
    (photon-predict-one model context)
    (should (photon-model-cache-get model key))
    (let ((cache-size (length (photon-model-cache model))))
      (photon-predict-one model context)
      (should (= (length (photon-model-cache model)) cache-size)))
    (photon-update-output-head model
                               (cdr (assq 'state (photon-predict-one model context)))
                               1 2 0.1)
    (should (= (length (photon-model-cache model)) 0))))

(ert-deftest photon-cache-stats-track-hit-miss-by-kind ()
  (let* ((photon-vector-backend (photon-make-elisp-vector-backend))
         (config (photon-make-config 8 8 4 2))
         (model (photon-make-model config))
         (context '(1 2 3 4)))
    (photon-model-clear-cache model)
    (photon-model-reset-cache-stats model)
    (photon-predict-one model context)
    (photon-predict-one model context)
    (let ((stats (photon-model-cache-stats model)))
      (should (> (photon-cache-stats-get stats 'hits) 0))
      (should (> (photon-cache-stats-get stats 'misses) 0))
      (should (= (photon-cache-stats-kind-get stats 'prediction-window 'misses) 1))
      (should (= (photon-cache-stats-kind-get stats 'prediction-window 'hits) 1))
      (should (> (photon-cache-stats-kind-get stats 'projection 'puts) 0)))
    (photon-model-clear-cache model)
    (should (= (photon-cache-stats-get (photon-model-cache-stats model)
                                       'clears)
               1))))

(ert-deftest photon-model-chunker-caches-chunk-state ()
  (let* ((photon-vector-backend (photon-make-elisp-vector-backend))
         (config (photon-make-config 8 8 4 2))
         (model (photon-make-model config))
         (chunk '(1 2 3 4)))
    (photon-model-clear-cache model)
    (photon-model-reset-cache-stats model)
    (photon-model-chunker model chunk)
    (photon-model-chunker model chunk)
    (let ((stats (photon-model-cache-stats model)))
      (should (= (photon-cache-stats-kind-get stats 'chunk-state 'misses) 1))
      (should (= (photon-cache-stats-kind-get stats 'chunk-state 'hits) 1)))))

(ert-deftest photon-forward-model-reuses-incremental-prefix ()
  (let* ((photon-vector-backend (photon-make-elisp-vector-backend))
         (config (photon-make-config 8 8 3 2))
         (incremental-model (photon-make-model config))
         (full-model (photon-make-model config))
         (short '(1 2 3))
         (extended '(1 2 3 4)))
    (photon-forward-model incremental-model short)
    (let ((incremental-states (photon-forward-model incremental-model extended))
          (full-states (photon-forward-model full-model extended))
          (last-info (photon-model-cache-get
                      incremental-model
                      (photon-incremental-forward-cache-key))))
      (should (equal incremental-states full-states))
      (should (cdr (assq 'incremental last-info)))
      (should (= (cdr (assq 'reused-chunks last-info)) 1)))))

(ert-deftest photon-model-cache-limit-trims-old-entries ()
  (let* ((photon-vector-backend (photon-make-elisp-vector-backend))
         (config (photon-make-config 16 8 4 2))
         (model (photon-make-model config))
         (i 0))
    (photon-model-set-cache-limit model 5)
    (while (< i 10)
      (photon-model-token-embedding model i)
      (setq i (1+ i)))
    (should (<= (length (photon-model-cache model)) 5))))

(ert-deftest photon-loss-report-separates-training-signals ()
  (let* ((photon-vector-backend (photon-make-elisp-vector-backend))
         (config (photon-make-config 8 8 4 2))
         (model (photon-make-model config))
         (report (photon-loss-report model '(1 2 3 4) 1)))
    (should (assq 'next-token-loss report))
    (should (assq 'memory-hit report))
    (should (assq 'reconstruction-loss report))
    (should (assq 'next-context-loss report))
    (should (>= (cdr (assq 'next-token-loss report)) 0))
    (should (>= (cdr (assq 'reconstruction-loss report)) 0))
    (should (>= (cdr (assq 'next-context-loss report)) 0.0))))

(ert-deftest photon-next-context-loss-counts-adjacent-chunks ()
  (let* ((photon-vector-backend (photon-make-elisp-vector-backend))
         (config (photon-make-config 8 8 2 2))
         (model (photon-make-model config))
         (report (photon-loss-report model '(1 2 3 4) 1)))
    (should (= (cdr (assq 'next-context-total report)) 1))
    (should (>= (cdr (assq 'next-context-loss report)) 0))))

(ert-deftest photon-evaluate-returns-loss-breakdown ()
  (let* ((config (photon-make-config 8 8 4 2))
         (model (photon-make-model config))
         (corpus '(1 2 3 4 1 2 3 4))
         (result (photon-evaluate model corpus 4))
         (loss (cdr (assq 'loss result))))
    (should (= (cdr (assq 'total result)) 4))
    (should (assq 'next-token-loss loss))
    (should (assq 'reconstruction-loss-permil loss))
    (should (assq 'next-context-loss-permil loss))))

(ert-deftest photon-loss-breakdown-includes-weighted-total ()
  (let* ((config (photon-make-config 8 8 4 2))
         (model (photon-make-model config))
         (result (photon-evaluate model '(1 2 3 4 1 2 3 4) 4))
         (loss (cdr (assq 'loss result))))
    (should (assq 'weighted-next-token-loss loss))
    (should (assq 'weighted-reconstruction-loss loss))
    (should (assq 'weighted-next-context-loss loss))
    (should (assq 'total-loss loss))
    (should (= (cdr (assq 'total-loss loss))
               (+ (cdr (assq 'weighted-next-token-loss loss))
                  (cdr (assq 'weighted-reconstruction-loss loss))
                  (cdr (assq 'weighted-next-context-loss loss)))))))

(ert-deftest photon-reconstruction-update-changes-reconstruction-head ()
  (let* ((photon-vector-backend (photon-make-elisp-vector-backend))
         (config (photon-make-config 8 8 4 2))
         (model (photon-make-model config))
         (zero-head nil)
         (i 0))
    (while (< i 8)
      (setq zero-head (cons (photon-vector-zeros 8) zero-head))
      (setq i (1+ i)))
    (photon-model-set-reconstruction-head model (nreverse zero-head))
    (let* ((report (photon-loss-report model '(1 2 3 4) 1))
           (before-output-head (copy-tree (photon-model-output-head model)))
           (before-head (copy-tree (photon-model-reconstruction-head model)))
           (before-mix (photon-model-param-get model 'decoder-token-mix))
           (before-gain (photon-vector-to-list
                         (photon-model-gain-get model 'decoder-prev-gain))))
      (photon-update-reconstruction-from-report model '(1 2 3 4) report 0.20)
      (should (equal before-output-head (photon-model-output-head model)))
      (should-not (equal before-head (photon-model-reconstruction-head model)))
      (should-not (= before-mix (photon-model-param-get model 'decoder-token-mix)))
      (should-not (equal before-gain
                         (photon-vector-to-list
                          (photon-model-gain-get model 'decoder-prev-gain)))))))

(ert-deftest photon-next-context-update-changes-context-parameters ()
  (let* ((photon-vector-backend (photon-make-elisp-vector-backend))
         (config (photon-make-config 8 8 2 2))
         (model (photon-make-model config))
         (report (photon-loss-report model '(1 2 3 4) 1))
         (before-gain (photon-vector-to-list
                       (photon-model-gain-get model 'context-current-gain)))
         (before-proj (copy-tree (photon-model-projection-get model
                                                              'context-proj))))
    (photon-update-next-context-from-report model report 0.20)
    (should-not (equal before-gain
                       (photon-vector-to-list
                        (photon-model-gain-get model 'context-current-gain))))
    (should-not (equal before-proj
                       (photon-model-projection-get model 'context-proj)))))

(ert-deftest photon-model-training-improves-toy-corpus ()
  (let* ((config (photon-make-config 8 8 4 2))
         (model (photon-make-model config))
         (corpus '(1 2 3 4 1 2 3 4 1 2 3 4 1 2 3 4))
         (before (cdr (assq 'correct (photon-evaluate model corpus 4)))))
    (photon-train model corpus 4 10 0.20)
    (let ((after (cdr (assq 'correct (photon-evaluate model corpus 4)))))
      (should (>= after before)))))

(ert-deftest photon-char-vocab-encodes-and-decodes-text ()
  (let* ((vocab (photon-build-char-vocab "abac"))
         (tokens (photon-encode-text vocab "cab")))
    (should (equal vocab '("a" "b" "c")))
    (should (equal (photon-decode-tokens vocab tokens) "cab"))))

(ert-deftest photon-wordpiece-tokenizer-round-trips-text ()
  (let* ((text "photon stream\nnext photon")
         (vocab (photon-build-wordpiece-vocab text 3))
         (tokens (photon-encode-wordpiece-text vocab text 3)))
    (should (equal (photon-take vocab 4)
                   (photon-wordpiece-special-tokens)))
    (should (member "pho" vocab))
    (should (member "##ton" vocab))
    (should (< (length tokens) (length text)))
    (should (equal (photon-decode-wordpiece-tokens vocab tokens) text))))

(ert-deftest photon-wordpiece-tokenizer-handles-specials-and-unknown ()
  (let* ((vocab (photon-build-wordpiece-vocab "known" 3))
         (tokens (photon-encode-wordpiece-text vocab "zzz" 3 t)))
    (should (= (car tokens) (photon-vocab-index vocab "[BOS]")))
    (should (= (car (last tokens)) (photon-vocab-index vocab "[EOS]")))
    (should (photon-member-equal-p (photon-vocab-index vocab "[UNK]")
                                   tokens))))

(ert-deftest photon-wordpiece-vocab-save-load-round-trips ()
  (let* ((vocab (photon-build-wordpiece-vocab "photon stream" 4))
         (path (make-temp-file "photon-vocab-" nil ".el")))
    (unwind-protect
        (progn
          (photon-save-vocab vocab path '((tokenizer . wordpiece)))
          (should (equal vocab (photon-load-vocab path))))
      (when (file-exists-p path)
        (delete-file path)))))

(ert-deftest photon-wordpiece-dataset-loader-reuses-vocab-path ()
  (let ((train-path (make-temp-file "photon-wp-train-" nil ".txt"
                                    "photon stream"))
        (eval-path (make-temp-file "photon-wp-eval-" nil ".txt"
                                   "stream photon"))
        (vocab-path (make-temp-file "photon-wp-vocab-" nil ".el")))
    (delete-file vocab-path)
    (unwind-protect
        (let* ((train (photon-load-batch-dataset-text-file
                       train-path 3
                       (list (cons 'tokenizer 'wordpiece)
                             (cons 'vocab-path vocab-path))))
               (eval (photon-load-batch-dataset-text-file
                      eval-path 3
                      (list (cons 'tokenizer 'wordpiece)
                            (cons 'vocab-path vocab-path)))))
	          (should (file-exists-p vocab-path))
	          (should (equal (cdr (assq 'vocab train))
	                         (cdr (assq 'vocab eval))))
                  (should (assq 'unknown-token-count
                                (cdr (assq 'token-diagnostics eval))))
                  (should (assq 'rare-token-count
                                (cdr (assq 'token-diagnostics eval))))
	          (should (> (cdr (assq 'token-count eval)) 0)))
      (when (file-exists-p train-path)
        (delete-file train-path))
      (when (file-exists-p eval-path)
        (delete-file eval-path))
      (when (file-exists-p vocab-path)
        (delete-file vocab-path)))))

(ert-deftest photon-batch-dataset-loader-can-limit-source-chars ()
  (let ((data-path (make-temp-file "photon-limited-data-" nil ".txt"
                                   "abcdefghij")))
    (unwind-protect
        (let ((dataset
               (photon-load-batch-dataset-text-file
                data-path 2 '((max-chars . 4)))))
          (should (= (cdr (assq 'source-chars dataset)) 10))
          (should (= (cdr (assq 'used-chars dataset)) 4))
          (should (= (cdr (assq 'token-count dataset)) 4)))
      (when (file-exists-p data-path)
        (delete-file data-path)))))

(ert-deftest photon-wordpiece-token-kind-classifies-pieces ()
  (let ((vocab '("[PAD]" "[UNK]" "[BOS]" "[EOS]" "p" "pho" "##ton")))
    (should (eq (photon-wordpiece-token-kind vocab 1) 'unknown))
    (should (eq (photon-wordpiece-token-kind vocab 2) 'special))
    (should (eq (photon-wordpiece-token-kind vocab 4) 'short-piece))
    (should (eq (photon-wordpiece-token-kind vocab 5) 'long-piece))
    (should (eq (photon-wordpiece-token-kind vocab 6) 'long-piece))
    (should (photon-wordpiece-token-continuation-p vocab 6))
    (should (= (photon-wordpiece-token-length vocab 6) 3))))

(ert-deftest photon-wordpiece-update-scale-boosts-long-rare-tokens ()
  (let* ((config (photon-make-config 8 8 4 2))
         (model (photon-make-model config))
         (short-token 4)
         (long-token 5))
    (photon-model-metadata-put
     model 'vocab '("[PAD]" "[UNK]" "[BOS]" "[EOS]" "p" "phot"))
    (photon-model-metadata-put model 'tokenizer 'wordpiece)
    (should (> (photon-wordpiece-update-scale model long-token)
               (photon-wordpiece-update-scale model short-token)))
    (photon-model-metadata-put model 'tokenizer 'char)
    (should (= (photon-wordpiece-update-scale model long-token) 1.0))))

(ert-deftest photon-wordpiece-generation-adjusts-repeat-and-continuation ()
  (let* ((config (photon-make-config 6 6 3 2))
         (model (photon-make-model config))
         (vocab '("[PAD]" "[UNK]" "[BOS]" "[EOS]" "phot" "##on"))
         (logits '(0.0 0.0 0.0 0.0 10.0 10.0)))
    (photon-model-metadata-put model 'vocab vocab)
    (photon-model-metadata-put model 'tokenizer 'wordpiece)
    (let ((adjusted (photon-generation-adjust-logits model '(4 4 5 5) logits)))
      (should (< (nth 1 adjusted) -999999.0))
      (should (< (nth 5 adjusted) (nth 5 logits)))
      (should (<= (nth 4 adjusted) (nth 4 logits))))))

(ert-deftest photon-wordpiece-readout-bias-boosts-long-rare-ngram-signal ()
  (let* ((config (photon-make-config 7 6 3 2))
         (model (photon-make-model config))
         (vocab '("[PAD]" "[UNK]" "[BOS]" "[EOS]" "p" "phot" "##long"))
         (source '(0.0 0.0 0.0 0.0 0.2 0.5 0.5))
         bias)
    (photon-model-metadata-put model 'vocab vocab)
    (photon-model-metadata-put model 'tokenizer 'wordpiece)
    (photon-model-param-set model 'wordpiece-readout-bias-enabled 1.0)
    (setq bias (photon-wordpiece-readout-bias-logits model source))
    (should (> (nth 6 bias) (nth 4 bias)))
    (should (> (nth 6 bias) 0.0))))

(ert-deftest photon-generation-sampling-supports-top-k-and-penalty ()
  (let* ((config (photon-make-config 6 6 3 2))
         (model (photon-make-model config))
         (generated
          (photon-model-generate
           model '(1 2 3) 2
           '((mode . sample) (temperature . 0.8) (top-k . 3)
             (repetition-penalty . 1.2)))))
    (should (= (length generated) 5))
    (should (integerp (car (last generated))))))

(ert-deftest photon-sampling-does-not-always-pick-masked-first-index ()
  (let ((token (photon-sample-index
                '(-1000000000.0 10.0 0.0)
                '((mode . sample) (temperature . 1.0))
                nil)))
    (should (= token 1))))

(ert-deftest photon-wordpiece-training-generates-text ()
  (let* ((photon-vector-backend (photon-make-elisp-vector-backend))
         (text "photon stream\nphoton checked\n")
         (result (photon-train-wordpiece-text text 2 6 2 1 0.20 4))
         (model (cdr (assq 'model result))))
    (should (eq (photon-model-metadata-get model 'tokenizer) 'wordpiece))
    (should (= (photon-model-param-get model 'context-anchor-ngram-weight) 6.0))
    (should (> (length (cdr (assq 'tokens result))) 0))
    (should (stringp (photon-model-generate-text model "photon" 2)))))

(ert-deftest photon-wordpiece-diagnostics-report-fallback-misses ()
  (let* ((photon-vector-backend (photon-make-elisp-vector-backend))
         (text "photon stream\nnext photon\n")
         (result (photon-train-wordpiece-text text 2 6 2 1 0.20 4))
         (model (cdr (assq 'model result)))
         (tokens (cdr (assq 'tokens result)))
         (diagnostics (photon-wordpiece-diagnostics model tokens 2 4)))
    (should (> (cdr (assq 'total diagnostics)) 0))
    (should (assq 'summary diagnostics))
    (should (consp (cdr (assq 'token-kinds diagnostics))))
    (should (consp (cdr (assq 'readout-ablations diagnostics))))
    (should (assq 'unknown-targets (cdr (assq 'summary diagnostics))))
    (should (assq 'rare-targets (cdr (assq 'summary diagnostics))))
    (should (listp (cdr (assq 'fallback-miss-summary diagnostics))))
    (when (cdr (assq 'fallback-misses diagnostics))
      (let ((record (car (cdr (assq 'fallback-misses diagnostics)))))
        (should (assq 'index record))
        (should (assq 'target-piece record))
        (should (assq 'target-kind record))
        (should (assq 'target-count record))
        (should (assq 'target-rare record))
        (should (assq 'memory-hit record))
        (should (assq 'top-5 record))
        (should (assq 'readout-contributions record))))))

(ert-deftest photon-text-training-attaches-vocab-metadata ()
  (let* ((result (photon-train-text "abababababab" 4 8 4 6 0.20))
         (model (cdr (assq 'model result)))
         (vocab (photon-model-metadata-get model 'vocab))
         (generated (photon-model-generate-text model "ab" 4)))
    (should (equal vocab '("a" "b")))
    (should (stringp generated))
    (should (= (length generated) 6))))

(ert-deftest photon-model-generation-trace-reports-top-k ()
  (let* ((result (photon-train-text "abababababab" 4 8 4 2 0.20))
         (model (cdr (assq 'model result)))
         (trace-result
          (photon-model-generate-text-with-trace model "ab" 3))
         (trace (cdr (assq 'trace trace-result))))
    (should (= (length trace) 3))
    (should (stringp (cdr (assq 'generated trace-result))))
    (should (assq 'top-5 (car trace)))
    (should (assq 'readout-contributions (car trace)))
    (should (stringp (cdr (assq 'prediction-char (car trace)))))))

(ert-deftest photon-model-generation-trace-accepts-sampling-options ()
  (let* ((result (photon-train-text "abababababab" 4 8 4 2 0.20))
         (model (cdr (assq 'model result)))
         (options '((mode . sample) (temperature . 0.9) (top-k . 2)
                    (repetition-penalty . 1.1)))
         (trace-result
          (photon-model-generate-text-with-trace model "ab" 3 options))
         (trace (cdr (assq 'trace trace-result))))
    (should (equal (cdr (assq 'options trace-result)) options))
    (should (equal (cdr (assq 'options (car trace))) options))
    (should (eq (cdr (assq 'mode (car trace))) 'sample))
    (should (= (length trace) 3))))

(ert-deftest photon-read-text-file-loads-corpus ()
  (let ((path (make-temp-file "photon-corpus-" nil ".txt" "abcabc")))
    (unwind-protect
        (should (equal (photon-read-text-file path) "abcabc"))
      (when (file-exists-p path)
        (delete-file path)))))

(ert-deftest photon-stream-text-file-trains-with-small-read-chunks ()
  (let ((path (make-temp-file "photon-stream-corpus-" nil ".txt"
                              "abcabc abcabc abcabc")))
    (unwind-protect
        (let* ((result (photon-train-text-file-stream path 3 6 3 1 0.20 4))
               (model (cdr (assq 'model result)))
               (before (cdr (assq 'before result)))
               (after (cdr (assq 'after result))))
          (should (equal (photon-model-metadata-get model 'tokenizer)
                         'char-stream))
          (should (= (photon-model-metadata-get model 'stream-chunk-bytes) 4))
          (should (> (cdr (assq 'total before)) 0))
          (should (> (cdr (assq 'total after)) 0)))
      (when (file-exists-p path)
        (delete-file path)))))

(ert-deftest photon-stream-text-file-split-evaluates-heldout ()
  (let ((train-path (make-temp-file "photon-stream-train-" nil ".txt"
                                    "abcabc abcabc abcabc"))
        (eval-path (make-temp-file "photon-stream-eval-" nil ".txt"
                                   "bcabca bcabca bcabca")))
    (unwind-protect
        (let* ((result (photon-train-text-file-stream-split
                        train-path eval-path 3 6 3 1 0.20 4))
               (model (cdr (assq 'model result)))
               (after (cdr (assq 'after result)))
               (fallback-after (cdr (assq 'fallback-after result))))
          (should (equal (photon-model-metadata-get model 'tokenizer)
                         'char-stream))
          (should (photon-model-metadata-get model 'eval-path))
          (should (> (cdr (assq 'total after)) 0))
          (should (> (cdr (assq 'total fallback-after)) 0)))
      (when (file-exists-p train-path)
        (delete-file train-path))
      (when (file-exists-p eval-path)
        (delete-file eval-path)))))

(ert-deftest photon-stream-file-diagnostics-reports-ranking-and-classes ()
  (let ((train-path (make-temp-file "photon-stream-diag-train-" nil ".txt"
                                    "abc abc abc abc"))
        (eval-path (make-temp-file "photon-stream-diag-eval-" nil ".txt"
                                   "bca bca bca")))
    (unwind-protect
        (let* ((result (photon-train-text-file-stream-split
                        train-path eval-path 3 6 3 1 0.20 4))
               (model (cdr (assq 'model result)))
               (vocab (cdr (assq 'vocab result)))
               (diagnostics
                (photon-stream-file-diagnostics
                 model eval-path vocab 3 4 3)))
          (should (> (cdr (assq 'total diagnostics)) 0))
          (should (assq 'fallback-accuracy-permil diagnostics))
          (should (assq 'top-3-accuracy-permil diagnostics))
          (should (assq 'top-5-accuracy-permil diagnostics))
          (should (assq 'average-target-margin diagnostics))
          (should (assq 'memory-hits diagnostics))
          (should (assq 'newline-fallback-accuracy-permil diagnostics))
          (should (assq 'newline-top-3-accuracy-permil diagnostics))
          (should (assq 'newline-average-target-margin diagnostics))
          (should (assq 'summary diagnostics))
          (should (assq 'readout-ablations diagnostics))
          (should (assq 'readout-component-gaps diagnostics))
          (should (assq 'ngram-head-gap-summary diagnostics))
          (should (assq 'ngram-head-gaps diagnostics))
          (should (assq 'fallback-miss-summary diagnostics))
          (should (listp (cdr (assq 'newline-targets diagnostics))))
          (should (consp (cdr (assq 'char-classes diagnostics))))
          (let ((ablations (cdr (assq 'readout-ablations diagnostics)))
                (has-full nil)
                (has-linear-output-head nil)
                (has-output-head-prototype nil)
                (has-raw-output-head nil)
                (has-output-head nil)
                (has-raw-prototype nil)
                (has-prototype nil)
                (has-state-cluster nil)
                (has-embedding nil)
                (has-structural-off nil))
            (while ablations
              (when (eq (cdr (assq 'mode (car ablations))) 'full)
                (setq has-full t))
              (when (eq (cdr (assq 'mode (car ablations)))
                        'linear-output-head-only)
                (setq has-linear-output-head t))
              (when (eq (cdr (assq 'mode (car ablations)))
                        'output-head-prototype-only)
                (setq has-output-head-prototype t))
              (when (eq (cdr (assq 'mode (car ablations)))
                        'raw-output-head-only)
                (setq has-raw-output-head t))
              (when (eq (cdr (assq 'mode (car ablations)))
                        'output-head-only)
                (setq has-output-head t))
              (when (eq (cdr (assq 'mode (car ablations)))
                        'raw-prototype-only)
                (setq has-raw-prototype t))
              (when (eq (cdr (assq 'mode (car ablations)))
                        'prototype-only)
                (setq has-prototype t))
              (when (eq (cdr (assq 'mode (car ablations)))
                        'state-cluster-only)
                (setq has-state-cluster t))
              (when (eq (cdr (assq 'mode (car ablations)))
                        'embedding-anchor-only)
                (setq has-embedding t))
              (when (eq (cdr (assq 'mode (car ablations)))
                        'structural-off)
                (setq has-structural-off t))
              (setq ablations (cdr ablations)))
            (should has-full)
            (should has-linear-output-head)
            (should has-output-head-prototype)
            (should has-raw-output-head)
            (should has-output-head)
            (should has-raw-prototype)
            (should has-prototype)
            (should has-state-cluster)
            (should has-embedding)
            (should has-structural-off))
          (let ((gaps (cdr (assq 'readout-component-gaps diagnostics))))
            (should (consp gaps))
            (should (assq 'ngram-head-gap (car gaps)))
            (should (assq 'average-head-margin (car gaps))))
          (when (cdr (assq 'fallback-miss-summary diagnostics))
            (let* ((record (car (cdr (assq 'fallback-miss-summary
                                           diagnostics))))
                   (contributions
                    (cdr (assq 'readout-contributions record)))
                   (has-prototype-contribution nil))
              (should (assq 'readout-contributions record))
              (should (assq 'component (car contributions)))
              (while contributions
                (when (eq (cdr (assq 'component (car contributions)))
                          'prototype)
                  (setq has-prototype-contribution t))
                (setq contributions (cdr contributions)))
              (should has-prototype-contribution)))
          (should (listp (cdr (assq 'fallback-misses diagnostics)))))
      (when (file-exists-p train-path)
        (delete-file train-path))
      (when (file-exists-p eval-path)
        (delete-file eval-path)))))

(ert-deftest photon-model-generation-returns-extended-prompt ()
  (let* ((config (photon-make-config 8 8 4 2))
         (model (photon-make-model config))
         (generated (photon-model-generate model '(1 2 3 4) 3)))
    (should (= (length generated) 7))))

(ert-deftest photon-save-load-round-trips-model ()
  (let* ((config (photon-make-config 8 8 4 2))
         (model (photon-make-model config))
         (path (make-temp-file "photon-model-" nil ".el")))
    (unwind-protect
        (progn
          (photon-save-model model path)
          (should (equal model (photon-load-model path)))
          (with-temp-buffer
            (insert-file-contents path)
            (goto-char (point-min))
            (let ((data (read (current-buffer))))
              (should (eq (cdr (assq 'format data)) 'photon-model-v1))
              (should (assq 'version data)))))
      (when (file-exists-p path)
        (delete-file path)))))

(ert-deftest photon-save-load-restores-vector-backend ()
  (let ((path (make-temp-file "photon-vector-model-" nil ".el")))
    (unwind-protect
        (progn
          (photon-use-elisp-vector-backend)
          (let ((model (photon-make-model (photon-make-config 8 8 4 2))))
            (photon-save-model model path))
          (photon-use-list-vector-backend)
          (let ((loaded (photon-load-model path)))
            (should (eq (photon-vector-backend-name) 'elisp-vector))
            (should (= (length (photon-model-generate loaded '(1 2 3 4) 2))
                       6))))
      (photon-use-list-vector-backend)
      (when (file-exists-p path)
        (delete-file path)))))

(ert-deftest photon-batch-options-checkpoint-and-resume ()
  (let* ((config (photon-make-config 8 8 4 2))
         (model (photon-make-model config))
         (tokens '(1 2 3 4 1 2 3 4 1 2 3 4))
         (path (make-temp-file "photon-checkpoint-" nil ".el")))
    (unwind-protect
        (let ((result
               (photon-train-batch-options
                model tokens 4 1 0.20 2
                (list (cons 'shuffle t)
                      (cons 'checkpoint-path path)
                      (cons 'train-split-numerator 3)
                      (cons 'train-split-denominator 4)))))
          (should (file-exists-p path))
          (should (> (cdr (assq 'train-pairs result)) 0))
          (should (> (cdr (assq 'eval-pairs result)) 0))
          (let ((resumed
                 (photon-train-batch-options
                  model tokens 4 1 0.10 2
                  (list (cons 'resume t)
                        (cons 'checkpoint-path path)))))
            (should (assq 'model resumed))
            (should (consp (cdr (assq 'history resumed))))))
      (when (file-exists-p path)
        (delete-file path)))))

(ert-deftest photon-training-history-round-trips ()
  (let* ((history (list (photon-training-history-entry
	                         0
	                         '((accuracy-permil . 250))
	                         '((accuracy-permil . 500)
                                   (fallback-accuracy-permil . 400)
                                   (loss . ((total . 1.0))))
	                         "checkpoint.el")))
         (path (make-temp-file "photon-history-" nil ".el")))
    (unwind-protect
        (progn
          (photon-save-training-history history path
                                        '((checkpoint-path . "checkpoint.el")))
          (should (equal history (photon-load-training-history path)))
          (should (= (photon-training-history-last-epoch history) 0)))
      (when (file-exists-p path)
        (delete-file path)))))

(ert-deftest photon-eval-better-prefers-fallback-on-loss-tie ()
  (let ((current '((accuracy-permil . 900)
                   (fallback-accuracy-permil . 500)
                   (loss . ((total-loss . 1000)))))
        (candidate '((accuracy-permil . 850)
                     (fallback-accuracy-permil . 625)
                     (loss . ((total-loss . 1000))))))
    (should (photon-eval-better-p candidate current))))

(ert-deftest photon-batch-dataset-loader-resumes-history-epochs ()
  (let ((data-path (make-temp-file "photon-batch-data-" nil ".txt"
                                   "abcd abcd abcd abcd"))
        (checkpoint-path (make-temp-file "photon-batch-checkpoint-" nil ".el"))
        (history-path (make-temp-file "photon-batch-history-" nil ".el")))
    (unwind-protect
        (let* ((dataset (photon-load-batch-dataset-text-file data-path 4))
               (config (photon-make-config
                        (length (cdr (assq 'vocab dataset))) 8 4 2))
               (model (photon-make-model config))
               (result
                (photon-train-batch-dataset
                 model dataset 2 0.20 2
                 (list (cons 'checkpoint-path checkpoint-path)
                       (cons 'history-path history-path))))
               (resumed
                (photon-train-batch-dataset
                 model dataset 1 0.10 2
                 (list (cons 'resume t)
                       (cons 'checkpoint-path checkpoint-path)
                       (cons 'history-path history-path))))
               (history (cdr (assq 'history resumed))))
          (should (file-exists-p checkpoint-path))
          (should (file-exists-p history-path))
          (should (> (cdr (assq 'token-count result)) 0))
          (should (= (car (nth 0 history)) 0))
	          (should (= (car (nth 1 history)) 1))
	          (should (= (car (nth 2 history)) 2))
	          (should (assq 'snapshot (cdr (nth 2 history))))
                  (should (assq 'eval-fallback-accuracy-permil
                                (cdr (assq 'snapshot
                                           (cdr (nth 2 history))))))
                  (should (assq 'epoch-elapsed-seconds
                                (cdr (assq 'snapshot
                                           (cdr (nth 2 history)))))))
      (when (file-exists-p data-path)
        (delete-file data-path))
      (when (file-exists-p checkpoint-path)
        (delete-file checkpoint-path))
      (when (file-exists-p history-path)
        (delete-file history-path)))))

(ert-deftest photon-batch-training-saves-best-checkpoint-and-csv-history ()
  (let ((data-path (make-temp-file "photon-best-data-" nil ".txt"
                                   "abcd abcd abcd abcd"))
        (checkpoint-path (make-temp-file "photon-best-checkpoint-" nil ".el"))
        (best-path (make-temp-file "photon-best-model-" nil ".el"))
        (history-path (make-temp-file "photon-best-history-" nil ".el"))
        (csv-path (make-temp-file "photon-best-history-" nil ".csv")))
    (unwind-protect
        (let* ((dataset (photon-load-batch-dataset-text-file data-path 4))
               (config (photon-make-config
                        (length (cdr (assq 'vocab dataset))) 8 4 2))
               (model (photon-make-model config))
               (result
                (photon-train-batch-dataset
                 model dataset 2 0.20 2
                 (list (cons 'checkpoint-path checkpoint-path)
                       (cons 'best-checkpoint-path best-path)
                       (cons 'history-path history-path)
                       (cons 'history-csv-path csv-path)))))
          (should (file-exists-p checkpoint-path))
          (should (file-exists-p best-path))
          (should (file-exists-p csv-path))
          (should (integerp (cdr (assq 'best-epoch result))))
          (with-temp-buffer
            (insert-file-contents csv-path)
	            (should (string-match-p "epoch,train_accuracy_permil"
	                                    (buffer-string)))
            (should (string-match-p "eval_fallback_accuracy_permil"
                                    (buffer-string)))
            (should (string-match-p "epoch_elapsed_seconds"
                                    (buffer-string)))
            (should (string-match-p "total_elapsed_seconds"
                                    (buffer-string)))
	            (should (string-match-p "\n0," (buffer-string)))))
      (when (file-exists-p data-path)
        (delete-file data-path))
      (when (file-exists-p checkpoint-path)
        (delete-file checkpoint-path))
      (when (file-exists-p best-path)
        (delete-file best-path))
      (when (file-exists-p history-path)
        (delete-file history-path))
      (when (file-exists-p csv-path)
        (delete-file csv-path)))))

(ert-deftest photon-wordpiece-best-checkpoint-restores-vocab-for-generation ()
  (let ((data-path (make-temp-file "photon-wp-best-data-" nil ".txt"
                                   "photon stream photon stream photon stream"))
        (checkpoint-path (make-temp-file "photon-wp-checkpoint-" nil ".el"))
        (best-path (make-temp-file "photon-wp-best-model-" nil ".el"))
        (history-path (make-temp-file "photon-wp-history-" nil ".el"))
        (csv-path (make-temp-file "photon-wp-history-" nil ".csv"))
        (vocab-path (make-temp-file "photon-wp-vocab-" nil ".el")))
    (delete-file vocab-path)
    (unwind-protect
        (let* ((dataset
                (photon-load-batch-dataset-text-file
                 data-path 4
                 (list (cons 'tokenizer 'wordpiece)
                       (cons 'vocab-path vocab-path)
                       (cons 'wordpiece-max-piece-size 4))))
               (config (photon-make-config
                        (length (cdr (assq 'vocab dataset))) 8 4 2))
               (model (photon-make-model config))
               (result
                (photon-train-batch-dataset
                 model dataset 2 0.20 2
                 (list (cons 'checkpoint-path checkpoint-path)
                       (cons 'best-checkpoint-path best-path)
                       (cons 'history-path history-path)
                       (cons 'history-csv-path csv-path))))
               (returned-model (cdr (assq 'model result)))
               (best-model (photon-load-model best-path))
               (saved-vocab (photon-load-vocab vocab-path)))
          (should (cdr (assq 'restored-best result)))
          (should (file-exists-p best-path))
          (should (file-exists-p vocab-path))
          (should (equal saved-vocab (cdr (assq 'vocab dataset))))
          (should (equal (photon-model-metadata-get best-model 'vocab)
                         saved-vocab))
          (should (assq 'unknown-token-count
                        (photon-model-metadata-get
                         best-model 'token-diagnostics)))
          (should (assq 'rare-token-count
                        (photon-model-metadata-get
                         best-model 'token-diagnostics)))
          (should (equal (photon-model-metadata-get returned-model 'vocab)
                         saved-vocab))
          (should (equal returned-model best-model))
          (should (stringp
                   (photon-model-generate-text
                    best-model "photon" 2 '((mode . greedy))))))
      (when (file-exists-p data-path)
        (delete-file data-path))
      (when (file-exists-p checkpoint-path)
        (delete-file checkpoint-path))
      (when (file-exists-p best-path)
        (delete-file best-path))
      (when (file-exists-p history-path)
        (delete-file history-path))
      (when (file-exists-p csv-path)
        (delete-file csv-path))
      (when (file-exists-p vocab-path)
        (delete-file vocab-path)))))

(ert-deftest photon-evaluate-pairs-does-not-update-memory ()
  (let* ((config (photon-make-config 8 8 4 2))
         (model (photon-make-model config))
         (pairs (photon-training-pairs '(1 2 3 4 1 2 3 4) 4))
         (before (length (photon-model-next-token-memory model))))
    (photon-evaluate-pairs model pairs)
    (should (= (length (photon-model-next-token-memory model)) before))))

(ert-deftest photon-evaluate-pairs-reports-fallback-accuracy ()
  (let* ((config (photon-make-config 8 8 4 2))
         (model (photon-make-model config))
         (pairs (photon-training-pairs '(1 2 3 4 1 2 3 4) 4))
         (result (photon-evaluate-pairs model pairs)))
    (should (assq 'fallback-accuracy-permil result))
    (should (assq 'fallback-top-3-accuracy-permil result))
    (should (assq 'fallback-top-5-accuracy-permil result))
    (should (assq 'memory-hit-permil result))))

(ert-deftest photon-evaluate-pairs-fallback-matches-standalone ()
  (let* ((config (photon-make-config 8 8 4 2))
         (model (photon-make-model config))
         (pairs (photon-training-pairs '(1 2 3 4 1 2 3 4) 4))
         (combined (photon-evaluate-pairs model pairs))
         (fallback (photon-evaluate-pairs-fallback model pairs))
         (fields '(fallback-correct
                   fallback-total
                   fallback-accuracy-permil
                   fallback-top-3-accuracy-permil
                   fallback-top-5-accuracy-permil
                   memory-hit-permil)))
    (while fields
      (should (equal (cdr (assq (car fields) combined))
                     (cdr (assq (car fields) fallback))))
      (setq fields (cdr fields)))))

(ert-deftest photon-multi-query-returns-token-id ()
  (let* ((config (photon-make-config 16 8 4 2))
         (token (photon-multi-query-next-token config '(1 3 5 7) 9)))
    (should (integerp token))
    (should (<= 0 token))
    (should (< token 16))))

(provide 'photon-test)

;;; photon-test.el ends here
