(load "lisp/photon.el")

(photon-use-elisp-vector-backend)

(let* ((config (photon-make-config 8 6 3 2))
       (model (photon-make-model config))
       (corpus '(1 2 3 1 2 3 1 2 3))
       (before-params (copy-tree (photon-model-architecture-params model)))
       (before (photon-evaluate model corpus 3))
       (history (photon-train model corpus 3 2 0.20))
       (after (photon-evaluate model corpus 3))
       (after-params (photon-model-architecture-params model)))
  (list (cons 'backend (photon-vector-backend-name))
        (cons 'params-changed (not (equal before-params after-params)))
        (cons 'before before)
        (cons 'history history)
        (cons 'after after)
        (cons 'param-count (length after-params))
        (cons 'generated (photon-model-generate model '(1 2 3) 3))))
