(load "lisp/photon.el")

(photon-use-elisp-vector-backend)

(let* ((config (photon-make-config 8 6 3 2))
       (model (photon-make-model config))
       (corpus '(1 2 3 1 2 3 1 2 3))
       (before-proj (copy-tree (photon-model-projection-get model 'chunk-proj)))
       (before (photon-evaluate model corpus 3))
       (history (photon-train model corpus 3 2 0.20))
       (after (photon-evaluate model corpus 3))
       (after-proj (photon-model-projection-get model 'chunk-proj)))
  (list (cons 'backend (photon-vector-backend-name))
        (cons 'projection-changed (not (equal before-proj after-proj)))
        (cons 'projection-shape (photon-projection-shape after-proj))
        (cons 'before before)
        (cons 'history history)
        (cons 'after after)
        (cons 'generated (photon-model-generate model '(1 2 3) 3))))
