(load-file (expand-file-name "../lisp/photon.el" (file-name-directory load-file-name)))

(let* ((config (photon-make-config 8 8 4 2))
       (model (photon-make-model config))
       (corpus '(1 2 3 4 1 2 3 4 1 2 3 4))
       (path "target/photon-model.el"))
  (make-directory "target" t)
  (photon-train model corpus 4 5 0.20)
  (photon-save-model model path)
  (let* ((loaded (photon-load-model path))
         (result (list (cons 'path path)
                       (cons 'generated (photon-model-generate loaded '(1 2 3 4) 4)))))
    (prin1 result)
    (princ "\n")))
