(load "lisp/photon.el")

(let* ((config (photon-make-config 8 4 2 2))
       (model (photon-make-model config))
       (corpus '(1 2 1 2))
       (before (photon-evaluate model corpus 2))
       (history (photon-train model corpus 2 1 0.20))
       (after (photon-evaluate model corpus 2))
       (generated (photon-model-generate model '(1 2) 2)))
  (list (cons 'before before)
        (cons 'before-loss (cdr (assq 'loss before)))
        (cons 'history history)
        (cons 'after after)
        (cons 'after-loss (cdr (assq 'loss after)))
        (cons 'generated generated)))
